#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=0.7.3a
PACKAGE=bwa
TOOL=$PACKAGE
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

singularity exec -B /ocean $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
